modLoader = "javafml"
loaderVersion = "[36,)"
license = "GPLv2"
issueTrackerURL="https://github.com/zbx1425/world-comment/issues"

[[mods]]
modId = "worldcomment"
version = "${version}"
displayName = "Subnoteica World Comment"
displayURL = "https://github.com/zbx1425/world-comment/"

authors = "Zbx1425"
description = "Subnoteica World Comment"
logoFile = "icon.png"

displayTest = "IGNORE_ALL_VERSION"

[[dependencies.worldcomment]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.worldcomment]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
